name: deploy to ifmk server

on: [push]

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    env: 
      CI: true
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v2
        with: 
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: copy to server
        uses: garygrossgarten/github-action-scp@release
        with: 
          local: dist
          remote: scp/sites/time.ly.quartztz.com
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
